### ISSUE TITLE
The argument type is reversed for input and output in the definition of the Element class

### ISSUE THREAD

**Issue by xueyue-sherry-zhang** [qua-platform/py-qua-tools#124]
https://github.com/qua-platform/py-qua-tools/blob/cdc35413d0fef2e58b6bade48697d06484209cf5/qualang_tools/config/components.py#L354

**Comment by SatyaBade12** [comment]
We've made the config builder such that is compatible with the current config, but I agree that this is confusing. Maybe we should change the names to 

```
class Element(ConfigBuilderElement):
    def __init__(
        self,
        name: str,
        element_analog_inputs: Optional[List[AnalogOutputPort]] = None,
        element_analog_outputs: Optional[List[AnalogInputPort]] = None,
        element_digital_inputs: Optional[List[DigitalOutputPort]] = None,
        element_digital_outputs: Optional[List[DigitalInputPort]] = None,
	...
```

what do you think? do you have any suggestion on how to make it clearer?

**Comment by xueyue-sherry-zhang** [comment]
Yes, I was wondering whether that’s because different point of view as well. It’s just I didn’t know which name comes from the config and which is from the controller. I think this renaming definitely makes things clearer. Just to clarify, somethingPort is always from the controller point of view?

         
Powered by Mailbutler <https://www.mailbutler.io/?utm_source=watermark&utm_medium=email&utm_campaign=watermark-variant-primary> - still your inbox, but smarter.

**Comment by SatyaBade12** [comment]
Thanks, we'll rename the arguments.
That's correct, all ports defined in `primitive_components.py` are from the controller's point of view.
