### ISSUE TITLE
digital input port id

### ISSUE THREAD

**Issue by xueyue-sherry-zhang** [qua-platform/py-qua-tools#131]
Hello,

I encountered this issue that even after havingthe digital input in the initialization, it still said `ConfigurationError("digital input port must be set first")`. I think the problem is in the initialization, the digital input port is labeled 'in1' anyways, but in the `set_digital_input_delay` function, it was trying to find f'in{port_id}'.

https://github.com/qua-platform/py-qua-tools/blob/cdc35413d0fef2e58b6bade48697d06484209cf5/qualang_tools/config/components.py#L431

Thanks,
Sherry

**Comment by SatyaBade12** [comment]
Hi Sherry,

Thanks for reporting the bug. The fix is available in the branch `compatibility-config-schema-0.3.8-alpha1`. Please use this branch until we release a new version.
