### ISSUE TITLE
"measure" vs "measurement"

### ISSUE THREAD

**Issue by JaseungKu** [qua-platform/py-qua-tools#139]
Hello, 

I'm not sure if this is really an issue, but I noticed that `MeasurePulse` class in the config module creates "measure", not "measurement" value for "operation" key as shown below. I don't see any error in running a qua program, so I image both are probably allowed, but the clarification would be appreciated. 

`        "readout_pulse_r0": {
            "operation": "measure",
            "length": 5000,
            "waveforms": {
                "I": "readout_I_wf_r0",
                "Q": "readout_Q_wf_r0"
            },`

Thanks,
Jaseung

**Comment by yomach** [comment]
Hi @JaseungKu,
Thanks for reporting the issue!

I believe that this was already fixed in 0.12.0, see these release notes:
https://github.com/qua-platform/py-qua-tools/releases

Can you please confirm?

Cheers,
Yoav

**Comment by JaseungKu** [comment]
Hi @yomach, 

Thanks for letting me know. You are right;  it got fixed in 0.12.0. I was using the 0.11.2 version and after upgrading to 0.12.0, I can see the "measurement" correctly. 

Best,
Jaseung
