### ISSUE TITLE
baking.py: digital marker

### ISSUE THREAD

**Issue by sherryue123** [qua-platform/py-qua-tools#18]
Hello,
I encountered a problem about digital marker when using baking. First, I tried to play an existing operation in the baking context. That operation has a digital marker 'ON'. However, the baked waveforms don't have 'digital marker' at all. I use the digital marker to trigger some switches so it's important to keep this attribute. I also tried to add_Op with argument digital_marker='ON'. However, it didn't get copied to the final configuration. I found the problem comes from the function _update_config. It didn't have the part to create 'digital_marker' at all. I'm doing some workaround now. Hope it can be fixed in the next version.
Thanks,
Sherry

**Comment by galwiner** [comment]
To resolve this, we need to bake a digital waveform alongside the analog one and then assign that as the digital marker of the element . 
shouldn't be too hard

**Comment by sherryue123** [comment]
Sounds good. I think it's good to distinguish whether it's from add_Op or an existing operation in the config. For our situation, the digital waveform is already there, for new operations, it's possible that we still want to use the existing digital waveforms or bake a new one.
