### ISSUE TITLE
Missing 'params' Parameter in get_correction_for_each_LO_and_IF Function

### ISSUE THREAD

**Issue by joanjcaceres** [qua-platform/py-qua-tools#225]
In the `/qualang_tools/octave_tools` module, the function `get_correction_for_each_LO_and_IF` is missing a `params` parameter. This parameter is necessary for the `qm.calibrate_element` function, which also accepts a params argument. The params argument is an instance of the `AutoCalibrationParams` class and allows specifying the amplitude of the IF to be calibrated.

**Comment by TheoLaudatQM** [comment]
Hi @joanjcaceres, thanks for reaching out!
In fact the function has already been updated and the fix should be available by updating the qualang-tools package: 
`pip install -U qualang-tools`.
Can you please update and tell us if it solves your issue?

**Comment by joanjcaceres** [comment]
Thank you! Now it works!
