### ISSUE TITLE
change default configBuilder GUI port from 8050

### ISSUE THREAD

**Issue by galwiner** [qua-platform/py-qua-tools#35]
config GUI currently uses 8050 as default port for serving. 
this clashes with Entropy default port. 
Let's change it to something else. 

@qguyk, is there a more robust solution?

**Comment by qguyk** [comment]
There are few things we can do:
1. use a different default port
2. when we start on default port, and it's bounded to another app, we can choose a different port automatically.
3. we can choose port automatically every time - but that's a question of the lifetime of the config GUI (if it's permanent - it's better to have a constant one)
4. we should raise a relevant error

**Comment by nikolaqm** [comment]
Now GUI:

1. uses by default port 8051, and after 3 seconds opens web browser
2. if port is used, it catches the error, stops browser timeout, and asks user to specify port by providing optional argument for port number they want to use
