### ISSUE TITLE
Remove uninitialized fields in the configuration

### ISSUE THREAD

**Issue by SatyaBade12** [qua-platform/py-qua-tools#58]
The final configuration generated by ConfigBuilder shouldn't contain empty dictionaries

**Comment by yomach** [comment]
Is this solved by your PR from yesterday?

**Comment by SatyaBade12** [comment]
Yes! outputPulseParameters field should not appear in the config if it is not used in an `Element` (we get an error in `load_schema`). But few other fields even when uninitialized do not cause errors, so I'm closing this now, we can create a new issue if any other uninitialized fields cause problems.
