### ISSUE TITLE
definition of Controller object in config builder

### ISSUE THREAD

**Issue by liorella-qm** [qua-platform/py-qua-tools#85]
when working with qualang_tools.config.components.Controller, I noticed a few things that require attention:

1. I see two types of methods: `analog_input` and his friends for output/digital and `use_analog_input_port` and his friends. For both of them, I don't really understand what they do... For `use_...`, what does "use" mean? Is it some kind of add? Also the idea that you can add if it doesn't exist, but return if it does, but still the `offset` parameter is there - that's confusing. Wouldn't it make more sense to just have an `add` and since the various ports are public members of this class, just be able to get them when needed?
2. There is no `offset` parameter in the context of digital outputs - digitals are binary. Does the config schema also define an offset for the digital input/output? If so this is a bug that also exists in QUA.
3. I am not sure the `int` option of the `__init__` method makes sense... We will never want to add ports "randomly" - ports always correspond to some actual connectivity we'd want... 
![image](https://user-images.githubusercontent.com/73523466/159241921-755674ce-5293-4329-8a1f-f1f8b6282a59.png)

**Comment by SatyaBade12** [comment]
The constructor of the `Controller` is modified to address 1 and 3, we should only open or use new ports using the methods `analog/digital_output/input` and that's all we need! (all other methods are prepended with an underscore).

According to the latest config schema, digital outputs have an offset. If this is a bug, please report it in qm-qua-sdk.
